# Site settings
title: Whit Richardson
email: whitrichardson@proton.me
description: Rediscovering the lost art of blogging. A space for thoughts, ideas, and reflections.
url: "https://whit.fyi" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  
# Only these are processed by Jekyll; everything else is copied as-is
include:
  - CNAME
  
# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md

# Collections
collections:
  posts:
    output: true

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

# Typography settings
kramdown:
  input: GFM
  syntax_highlighter: rouge
